<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Markdig" Version="0.23.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Kader.DataAccessLayer\Kader.Data.DataAccessLayer.csproj" />

  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

</Project>
